package:
  name: openopenmmreporters
  version: 0.1.0

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python  {{ python }}
    - setuptools
    - numpy 

  run:
    - python  {{ python }}
    - numpy
    - openmm

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful methods and classes to...
  dev_url: https://github.com/uibcdf/OpenOpenMMReporters
  doc_url: https://uibcdf.org/OpenOpenMMReporters

